/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de Lenguaje Arit en JAVACC */

package GramaticaJavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int RNULL = 9;
  /** RegularExpression Id. */
  int RTRUE = 10;
  /** RegularExpression Id. */
  int RFALSE = 11;
  /** RegularExpression Id. */
  int RIF = 12;
  /** RegularExpression Id. */
  int RELSE = 13;
  /** RegularExpression Id. */
  int RSWITCH = 14;
  /** RegularExpression Id. */
  int RCASE = 15;
  /** RegularExpression Id. */
  int RBREAK = 16;
  /** RegularExpression Id. */
  int RCONTINUE = 17;
  /** RegularExpression Id. */
  int RWHILE = 18;
  /** RegularExpression Id. */
  int RDO = 19;
  /** RegularExpression Id. */
  int RFOR = 20;
  /** RegularExpression Id. */
  int RIN = 21;
  /** RegularExpression Id. */
  int RFUNCTION = 22;
  /** RegularExpression Id. */
  int RRETURN = 23;
  /** RegularExpression Id. */
  int RDEFAULT = 24;
  /** RegularExpression Id. */
  int IGUAL = 25;
  /** RegularExpression Id. */
  int PARIZQ = 26;
  /** RegularExpression Id. */
  int PARDER = 27;
  /** RegularExpression Id. */
  int LLAVEIZQ = 28;
  /** RegularExpression Id. */
  int LLAVEDER = 29;
  /** RegularExpression Id. */
  int COMA = 30;
  /** RegularExpression Id. */
  int PTCOMA = 31;
  /** RegularExpression Id. */
  int DOSPUNTOS = 32;
  /** RegularExpression Id. */
  int CORIZQ = 33;
  /** RegularExpression Id. */
  int CORDER = 34;
  /** RegularExpression Id. */
  int FLECHA = 35;
  /** RegularExpression Id. */
  int MAS = 36;
  /** RegularExpression Id. */
  int MENOS = 37;
  /** RegularExpression Id. */
  int POR = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int POT = 40;
  /** RegularExpression Id. */
  int MOD = 41;
  /** RegularExpression Id. */
  int MENOR = 42;
  /** RegularExpression Id. */
  int MAYOR = 43;
  /** RegularExpression Id. */
  int MENORIGUAL = 44;
  /** RegularExpression Id. */
  int MAYORIGUAL = 45;
  /** RegularExpression Id. */
  int IGUALQUE = 46;
  /** RegularExpression Id. */
  int DIFERENTE = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int NOT = 50;
  /** RegularExpression Id. */
  int TERNARIO = 51;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 52;
  /** RegularExpression Id. */
  int STRING = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMERO>",
    "<DECIMAL>",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"continue\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"in\"",
    "\"function\"",
    "\"return\"",
    "\"default\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"=>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"?\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 54>",
    "\"\\\"\"",
  };

}
